name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake make g++ p7zip
    - name: Build shinobi
      shell: bash
      run: |
        echo $BOOST_ROOT_1_72_0
        mkdir build && cd build
        cmake -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0/include -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --parallel --config Release 
        ctest -vv
        strip shinobi
    - name: Create shinobi archive
      run: |
        mkdir artifact
        7z a artifact/shinobi-linux.zip ./build/shinobi

    # Upload shinobi binary archive as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: shinobi-binary-archives
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/shinobi-linux.zip
        asset_name: shinobi-linux.zip
        asset_content_type: application/zip
