name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: brew install re2c p7zip cmake

    - name: Build shinobi
      shell: bash
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --parallel --config Release
        ctest -vv

    - name: Create shinobi archive
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/shinobi-mac.zip ./build/shinobi

    # Upload shinobi binary archive as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: shinobi-binary-archives
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/shinobi-mac.zip
        asset_name: shinobi-mac.zip
        asset_content_type: application/zip
