name: Windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        choco install re2c 

    - name: Build shinobi
      shell: bash
      run: |
        mkdir build && cd build
        cmake -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_72_0/include -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --parallel --config Release
        ctest -vv

    - name: Create shinobi archive
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/shinobi-win.zip ./build/Release/shinobi.exe

    # Upload shinobi binary archive as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: shinobi-binary-archives
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/shinobi-win.zip
        asset_name: shinobi-win.zip
        asset_content_type: application/zip
